FROM n8nio/n8n:0.236.2

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_USER_MANAGEMENT_DISABLED=true
ENV EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
ENV EXECUTIONS_DATA_SAVE_ON_ERROR=all
ENV EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
ENV N8N_DIAGNOSTICS_ENABLED=false
ENV N8N_LOG_LEVEL=warn

EXPOSE 5678
